spring:
  application:
    name: subject
server:
  port: 8098
eureka:
  instance:
    hostname: localhost
#  prefer-ip-address: true    
#    lease-renewal-interval-in-seconds: 10
#   lease-expiration-duration-in-seconds: 20
  serviceUrl:
      defaultZone: http://localhost:8080/eureka
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka      

#Enable Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'